apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::632365610063:role/eksctl-eksctl-demo-nodegroup-ng-f-NodeInstanceRole-E5GNX5RNGU0H
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::632365610063:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-29T08:13:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1616"
  uid: fe893914-164c-4549-9907-bdf77810bdc5
